In [26]:
import pandas as pd 
import glob

In [59]:
#df1 = pd.read_csv('data/201901-citibike-tripdata.csv')
#df2 = pd.read_csv('data/201902-citibike-tripdata.csv')
#df3 = pd.read_csv('data/201903-citibike-tripdata.csv')
#df4 = pd.read_csv('data/201904-citibike-tripdata.csv')
#df5 = pd.read_csv('data/201905-citibike-tripdata.csv')
#df6 = pd.read_csv('data/201906-citibike-tripdata.csv')
#df7 = pd.read_csv('data/201907-citibike-tripdata.csv')
#df8 = pd.read_csv('data/201908-citibike-tripdata.csv')
#df9 = pd.read_csv('data/201909-citibike-tripdata.csv')
#df10 = pd.read_csv('data/201910-citibike-tripdata.csv')
#df11 = pd.read_csv('data/201911-citibike-tripdata.csv')
#df12 = pd.read_csv('data/201912-citibike-tripdata.csv')
#frame = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12]
#result = pd.concat(frame)

In [60]:
#glob.glob(pathname, *, recursive=False) Returns a list of pathnames
frames = [ pd.read_csv(f) for f in glob.glob('data/*.csv') ]

In [63]:
citibike_clean = pd.concat(frames)

In [64]:

citibike_clean.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1

In [76]:
# Sort by startime and keep it in place.  keep it as a dataframe instead of panda series
citibike_clean.sort_values("starttime",  ascending=True,inplace=False)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955205,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
955206,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
955207,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672816,-73.983524,27746,Subscriber,1935,2
955208,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
955209,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0

In [78]:
citibike_clean.count()

tripduration               20551697
starttime                  20551697
stoptime                   20551697
start station id           20551517
start station name         20551517
start station latitude     20551697
start station longitude    20551697
end station id             20551517
end station name           20551517
end station latitude       20551697
end station longitude      20551697
bikeid                     20551697
usertype                   20551697
birth year                 20551697
gender                     20551697
dtype: int64

In [77]:
# Export the clean citibike trip data into a csv
citibike_clean.to_csv("data/citibike_trip2019.csv",encoding='utf-8', index=False)